version: 2
jobs:
  build-image:

    machine:
      enabled: true

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: build docker image
          command: |
            set -ev
            ./pipe_build_up_test.sh
      - run:
          name: push tagged docker image to dockerhub
          command: |
            set -ev
            echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
            docker push cyberdojo/rack-base:latest
      - run:
          name: trigger dependent repos
          command: |
            set -ev
            ./sh/trigger_dependent_repos.sh "${CIRCLE_SHA1:0:7}" \
               https://github.com/cyber-dojo/differ.git    \
               https://github.com/cyber-dojo/saver.git     \
               https://github.com/cyber-dojo/zipper.git    \
               https://github.com/cyber-dojo/porter.git    \
               https://github.com/cyber-dojo/mapper.git    \
               https://github.com/cyber-dojo/ragger.git    \
               https://github.com/cyber-dojo/start-points-base.git
            # old architecture
            ./sh/trigger_dependent_repos.sh "${CIRCLE_SHA1:0:7}" \
               https://github.com/cyber-dojo/starter.git

workflows:
  version: 2
  build-publish:
    jobs:
      - build-image:
          context: cyberdojo-context
          filters:
            branches:
              only:
                  - master
