version: 2
jobs:
  build-image:

    machine:
      enabled: true

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: build docker image
          command: |
            set -ev
            ./pipe_build_up_test.sh
      - run:
          name: push tagged docker image to dockerhub
          command: |
            set -ev
            readonly project=${CIRCLE_PROJECT_REPONAME}
            docker tag  cyberdojo/${project}:latest cyberdojo/${project}:${CIRCLE_SHA1:0:7}
            docker tag  cyberdojo/${project}:latest cyberdojo/${project}:beta
            echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
            docker push cyberdojo/${project}:${CIRCLE_SHA1:0:7}
            docker push cyberdojo/${project}:beta
      - run:
          name: trigger dependent repos
          command: |
            set -ev
            #curl --fail -X POST https://circleci.com/api/v1.1/project/github/cyber-dojo/differ/build?circle-token=${CIRCLECI_BUILD_TOKEN}
            # curl --fail -X POST https://circleci.com/api/v1.1/project/github/cyber-dojo/saver/build?circle-token=${CIRCLECI_BUILD_TOKEN}
            # curl --fail -X POST https://circleci.com/api/v1.1/project/github/cyber-dojo/zipper/build?circle-token=${CIRCLECI_BUILD_TOKEN}
            # curl --fail -X POST https://circleci.com/api/v1.1/project/github/cyber-dojo/starter/build?circle-token=${CIRCLECI_BUILD_TOKEN}
            # curl --fail -X POST https://circleci.com/api/v1.1/project/github/cyber-dojo/start-points-base/build?circle-token=${CIRCLECI_BUILD_TOKEN}
            ../sh/trigger_dependent_repo.sh https://github.com/cyber-dojo/differ.git "${CIRCLE_SHA1:0:7}"

workflows:
  version: 2
  build-publish:
    jobs:
      - build-image:
          context: cyberdojo-context
          filters:
            branches:
              only:
                  - master
